version: 2.1

jobs:
  say-hello:
    resource_class: small
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: |
            wget https://papermc.io/api/v2/projects/paper/versions/1.21/builds/105/downloads/paper-1.21-105.jar
            sudo apt update &>/dev/null && echo "apt cache successfully updated" || echo "apt cache update failed, you might receive stale packages"
            sudo apt-get install openjdk-21-jre-headless &>/dev/null && echo "Yay! Openjdk17 has been successfully installed." || echo "Failed to install OpenJdk17."
            wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
            chmod +x cloudflared-linux-amd64
            ./cloudflared-linux-amd64 tunnel --url tcp://127.0.0.1:25565 & java -Xmx6144M -Xms6144M -jar paper-1.21-105.jar nogui

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
